# Numpy
## Ejercicios prácticos

---
### Utiliza Python y Numpy para realizar las siguientes operaciones:
1. Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.
2. Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
10. Crea un arreglo que contenga los números pares entre 30 y 70.
11. Crea una matriz identidad de 3x3.
12. Genera un número aleatorio entre 0 y 1.
13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

In [2]:
import numpy as np

In [15]:
# ejercicio 1
#Dado el arreglo a = np.array([1, 2, 3, 4]), determina si ninguno de los elementos es cero.
import numpy as np
a = np.array([1,2,3,4])
b = np.any(a==0)
if b == True:
    print("El arreglo contiene 0")
else:
    print("El arreglo no contiene 0")

El arreglo no contiene 0


In [19]:
# ejercicio 2
#Dado el arreglo a = np.array([0, 0, 2, 0]), determina si contiene algún elemento que no sea cero.
a = np.array([0,0,2,0])
b = np.any(a!=0)
if b == True:
    print("El arreglo contiene elementos que no son 0")
else:
    print("El arreglo solo contiene 0")

El arreglo contiene elementos que no son 0


In [24]:
# ejercicio 3
#Analiza el arreglo a = np.array([1, 2, np.nan, np.inf]) y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
a = np.array([1, 2, np.nan, np.inf])
b = np.isnan(a)
c = np.isinf(a)
d = np.any(b == True)
e = np.any(c == True)
if d == True:
    print("El arreglo contiene valores no numericos")
else:
    print("El arreglo solo contiene valores numericos")
if e == True:
    print("El arreglo contiene valores infinitos")
else:
    print("El arreglo solo contiene valores numericos")

El arreglo contiene valores no numericos
El arreglo contiene valores infinitos


In [25]:
# ejercicio 4
#Dado el arreglo a = np.array([1, 2, np.inf]), determina si contiene valores infinitos.
a = np.array([1, 2, np.inf])
c = np.isinf(a)
e = np.any(c == True)
if e == True:
    print("El arreglo contiene valores infinitos")
else:
    print("El arreglo solo contiene valores numericos")

El arreglo contiene valores infinitos


In [26]:
# ejercicio 5
# Dado el arreglo a = np.array([1, np.nan, 3]), determina si contiene valores NaN.
a = np.array([1, np.nan, 3])
b = np.isnan(a)
if d == True:
    print("El arreglo contiene valores no numericos")
else:
    print("El arreglo solo contiene valores numericos")


El arreglo contiene valores no numericos


In [27]:
# ejercicio 6
#Dados los arreglos a = np.array([1, 3, 5]) y b = np.array([2, 3, 4]), realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
a = np.array([1, 3, 5])
b = np.array([2, 3, 4])
res1 = a > b
res2 = a >= b
res3 = a < b
res4 = a <= b
print(res1)
print(res2)
print(res3)
print(res4)

[False False  True]
[False  True  True]
[ True False False]
[ True  True False]


In [32]:
# ejercicio 7
#Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
a = np.array([1, 7, 13, 105])
print(f"Cada elemento del arrglo consume {a.itemsize} bytes")




Cada elemento del arrglo consume 8 bytes


In [40]:
# ejercicio 8
#Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
a =np.zeros(10, dtype=int)
b =np.ones(10, dtype=int)
c = np.full(10,5)
d = np.full(10,1) #Forma adicional


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [43]:
# ejercicio 9
#Crea un arreglo que contenga todos los números enteros entre 30 y 70.
a =np.arange(30,71)
a

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [44]:
# ejercicio 10
#Crea un arreglo que contenga los números pares entre 30 y 70.
a = np.arange(30,71,2)
a

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [46]:
# ejercicio 11
#Crea una matriz identidad de 3x3.
a =np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [49]:
# ejercicio 12
#Genera un número aleatorio entre 0 y 1.
a =np.random.rand()
print(a)


0.5161153964457448


In [50]:
# ejercicio 13
#Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
a = np.random.randn(15)
print(a)

[-0.4862676  -0.7110243   0.98176137  0.51065351  0.01085797  1.93995486
  0.57196522 -1.62604732  2.13354515 -0.81454754  0.35428229 -1.12228252
 -0.71761936 -0.02266639  0.12665047]


In [58]:
# ejercicio 14
#Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
a=np.arange(15,56)
print(a[1:41])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]


In [69]:
# ejercicio 15
#Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.

a = np.linspace(start=5, stop=50, num=10, dtype=int)
print(a)


[ 5 10 15 20 25 30 35 40 45 50]


In [71]:
# ejercicio 16
#Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
a=np.arange(0,21)
print(a)
b =np.where ((a >= 9) & (a<=15))
print(b)
a[b] = a[b]*-1
print(a)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(array([ 9, 10, 11, 12, 13, 14, 15]),)
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [73]:
# ejercicio 17
#Convierte el arreglo a = np.array([1, 2, 3]) a una lista de Python.
a = np.array([1, 2, 3])
b =a.tolist()
print(b)

[1, 2, 3]


In [74]:
# ejercicio 18
#Convierte la lista l = [1, 2, 3] a un arreglo de Numpy.
l = [1, 2, 3]
a =np.array(l)
print(a)

[1 2 3]


In [80]:
# ejercicio 19
#Dada la matriz m = np.array([[1, 2], [3, 4]]), verifica qué números son pares y almacena los resultados en otra matriz.
m = np.array([[1, 2], [3, 4]])
b = np.where(m%2 == 0)
c = m[b]
print(c)


[2 4]


In [81]:
# ejercicio 20
#Dado el arreglo m = np.array([[1, 2, 3], [4, 5, 6]]), encuentra el número de filas y columnas de la matriz.
m = np.array([[1, 2, 3], [4, 5, 6]])
print(m.shape)


(2, 3)


# Ejercicios Resueltos EARP CIENCIA DE DATOS
